name: Build application

on: [push]

jobs:
  build:
    name: "Compilation and unit tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install -P !main,byteman4_compatible
  integration_tests:
    needs: [build]
    name: "Integration tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean install
  publish:
    name: "Publish to the Maven Central Repository"
    needs: [integration_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Publish to the Maven Central Repository
        if: startsWith(github.ref, 'refs/tags/v')
        run: .travis/release.sh
        env:
          MAVEN_USERNAME: '${{ secrets.BMUNIT_EXT_MAVEN_USERNAME }}'
          MAVEN_PASSWORD: '${{ secrets.BMUNIT_EXT_MAVEN_PASSWORD }}'
          ENCRYPTION_PASSWORD: '${{ secrets.BMUNIT_EXT_ENCRYPTION_PASSWORD }}'
          GPG_KEYNAME: '${{ secrets.BMUNIT_EXT_GPG_KEYNAME }}'
          GPG_PASSPHRASE: '${{ secrets.BMUNIT_EXT_GPG_PASSPHRASE }}'